kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-data
  namespace: postgres
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi